bucket         = "terraform-state-backend-575108961054"
key            = "cms/demo-cx/terraform.tfstate"
region         = "ap-southeast-2"
dynamodb_table = "terraform-state-backend-lock-575108961054"
encrypt = true
