bucket         = "terraform-state-backend-318108814388"
key            = "grus/dev/terraform.tfstate"
region         = "us-east-1"
dynamodb_table = "terraform-state-backend-lock-318108814388"
encrypt = true
